services:
  - type: web
    name: audio-extractor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    plan: free
    envVars:
      - key: PORT
        value: 10000
